---
Name: raygun-tags-processor
Before:
  - raygun
Only:
  envorconstant: 'SS_RAYGUN_APP_KEY'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushProcessor, [ '%$Springtimesoft\RaygunTags\Processor' ]]
